



#mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.operation.qkwall.entity


#spring
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pop_qkwall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    password: root
    username: root




#tomcat
server:
  servlet:
    context-path: /
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - image/png
    - image/jpeg
    - image/jpg
    - text/html
    - application/javascript
    - text/css
    - application/octet-stream
    - application/json
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto


#log
logging:
  path: log

#content
pvpgame:
  test: test
  #使任务生效的积分墙服务器接口路径
  serverUrl: http://localhost:8088/task/synchronizationTaskRemainingToRedisByTaskId
  #图片CDN地址+临时路径(/appIcon/)
  iconPath: https://d3cj7t4u9u6hxp.cloudfront.net/appIcon/

#最大连接数
http:
    maxTotal: 100
#并发数
    defaultMaxPerRoute: 20
#创建连接的最长时间
    connectTimeout: 30000
#从连接池中获取到连接的最长时间
    connectionRequestTimeout: 500
#数据传输的最长时间
    socketTimeout: 30000
#提交请求前测试连接是否可用
    staleConnectionCheckEnabled: true



